### ISSUE TITLE
generalizing region-of-interest inputs

### ISSUE THREAD

**Issue by sjneph** [alexpreynolds/byte-store#3]
I recommend that the -w option allow a file name in addition to its current support of a list of IDs.  If a file name, read a list of range IDs separated by commas or whitespace.  If a list of range IDs itself, process it directly.
This will allow us to get around string size limitations, and bytestore can process each range listed in the file separately (loading master index file only once).

**Comment by alexpreynolds** [comment]
Thanks! Refactored things just slightly to match variable naming style and error messaging in commit f49ece7
